[package]
name = "my_game"
version = "0.1.0"
authors = ["Brennen Garland <bgarland015@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD

specs = "0.16.1"
=======
specs = { version = "0.16.1", features = ["specs-derive"] }
>>>>>>> 52ce6b337abb67b669ab0fcdeff100d3de513ee0
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}